/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package l2m;

public class Gpu {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Gpu(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Gpu obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        voskJNI.delete_Gpu(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Gpu() {
    this(voskJNI.new_Gpu(), true);
  }

  public void Init() {
    voskJNI.Gpu_Init(swigCPtr, this);
  }

  public void Instantiate() {
    voskJNI.Gpu_Instantiate(swigCPtr, this);
  }

}
