/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package l2m;

public class LidModel {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected LidModel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LidModel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  public LidModel(String lid_path) {
    this(voskJNI.new_LidModel(lid_path), true);
  }

  public void Ref() {
    voskJNI.LidModel_Ref(swigCPtr, this);
  }

  public void Unref() {
    voskJNI.LidModel_Unref(swigCPtr, this);
  }

}
