/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package l2m;

public class voskJNI {

    static {
        System.loadLibrary("vosk_jni_cpu");
    }

  public final static native long new_KaldiRecognizer__SWIG_0(long jarg1, Model jarg1_, float jarg2);
  public final static native long new_KaldiRecognizer__SWIG_1(long jarg1, Model jarg1_, long jarg2, SpkModel jarg2_, float jarg3);
  public final static native long new_KaldiRecognizer__SWIG_2(long jarg1, LidModel jarg1_, float jarg2);
  public final static native long new_KaldiRecognizer__SWIG_3(long jarg1, Model jarg1_, float jarg2, String jarg3);
  public final static native void delete_KaldiRecognizer(long jarg1);
  public final static native boolean KaldiRecognizer_AcceptWaveform(long jarg1, KaldiRecognizer jarg1_, byte[] jarg2, int jarg3);
  public final static native String KaldiRecognizer_Result(long jarg1, KaldiRecognizer jarg1_);
  public final static native String KaldiRecognizer_LangResult(long jarg1, KaldiRecognizer jarg1_, byte[] jarg2, int jarg3);
  public final static native String KaldiRecognizer_FinalResult(long jarg1, KaldiRecognizer jarg1_);
  public final static native String KaldiRecognizer_PartialResult(long jarg1, KaldiRecognizer jarg1_);
  public final static native void KaldiRecognizer_Calculate(long jarg1, KaldiRecognizer jarg1_, byte[] jarg2, int jarg3);
  public final static native long new_Model(String jarg1);
  public final static native void Model_Ref(long jarg1, Model jarg1_);
  public final static native void Model_Unref(long jarg1, Model jarg1_);
  public final static native long new_SpkModel(String jarg1);
  public final static native void SpkModel_Ref(long jarg1, SpkModel jarg1_);
  public final static native void SpkModel_Unref(long jarg1, SpkModel jarg1_);
  public final static native long new_LidModel(String jarg1);
  public final static native void LidModel_Ref(long jarg1, LidModel jarg1_);
  public final static native void LidModel_Unref(long jarg1, LidModel jarg1_);
  public final static native long new_Gpu();
  public final static native void delete_Gpu(long jarg1);
  public final static native void Gpu_Init(long jarg1, Gpu jarg1_);
  public final static native void Gpu_Instantiate(long jarg1, Gpu jarg1_);
}
