/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package l2m.recognition.language;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class KaldiRecognizer {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected KaldiRecognizer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(KaldiRecognizer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        lidJNI.delete_KaldiRecognizer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void AcceptWaveform(byte[] data) {
    AcceptWaveform(data, data.length);
  }
  public void AcceptWaveform(short[] data, int len) {
    byte[] bdata = new byte[len * 2];
    ByteBuffer.wrap(bdata).order(ByteOrder.LITTLE_ENDIAN).asShortBuffer().put(data, 0, len);
    AcceptWaveform(bdata, bdata.length);
  }

  public KaldiRecognizer(LidModel model, float sample_rate) {
    this(lidJNI.new_KaldiRecognizer(LidModel.getCPtr(model), model, sample_rate), true);
  }

  public void AcceptWaveform(byte[] data, int len) {
    lidJNI.KaldiRecognizer_AcceptWaveform(swigCPtr, this, data, len);
  }

  public String LangResult() {
    return lidJNI.KaldiRecognizer_LangResult(swigCPtr, this);
  }

}
