/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package l2m.recognition.language;

public class lid {
  public static void SetLogLevel(int level) {
    lidJNI.SetLogLevel(level);
  }

}
