/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package l2m.recognition.language;

public class lidJNI {

    static {
        boolean loadedEmbeddedLibrary = EmbeddedLibraryTools.LOADED_EMBEDDED_LIBRARY;
    }

  public final static native long new_LidModel(String jarg1);
  public final static native void delete_LidModel(long jarg1);
  public final static native long new_KaldiRecognizer(long jarg1, LidModel jarg1_, float jarg2);
  public final static native void delete_KaldiRecognizer(long jarg1);
  public final static native void KaldiRecognizer_AcceptWaveform(long jarg1, KaldiRecognizer jarg1_, byte[] jarg2, int jarg3);
  public final static native String KaldiRecognizer_LangResult(long jarg1, KaldiRecognizer jarg1_);
  public final static native void SetLogLevel(int jarg1);
}
