/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package l2m.recognition.language;

public class LidModel {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected LidModel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LidModel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        lidJNI.delete_LidModel(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public LidModel(String model_path) {
    this(lidJNI.new_LidModel(model_path), true);
  }

}
